In [124]:
import numpy as np
import pandas as pd
from sound import *

df = pd.read_csv('parte_nome_sexo.csv')
df

df = df[df['PrimeiroNomeNoAccents'].notna()]
df = df[:1000]
df

     Masculino  Feminino PrimeiroNomeNoAccents
0            1         0              BENEDITO
1            1         0            Secretario
2            1         0                  LUIZ
3            1         0                DANIEL
4            1         0                MARCOS
5            1         0                  ADAO
6            1         0                WALDIR
7            0         1                 Sonia
8            1         0                MARCOS
9            0         1                Keviny
10           1         0               Valdeir
11           0         1                  LENI
12           1         0                  LUIS
13           1         0               EUGENIO
14           0         1                 CELIA
15           0         1                  Ilma
16           1         0                CARLOS
17           1         0                 Diego
18           0         1             NEUSALINA
19           0         1               Evelini
20           1         0                CARLOS
21           1         0                Odemir
22           1         0               JOSENIL
23           1         0              Adeilton
24           1         0              Benjamin
25           1         0              EDMILSON
26           1         0                 EDSON
27           1         0              Anderson
28           1         0                FLAVIO
29           1         0                  Joao
..         ...       ...                   ...
970          0         1                   ANA
971          1         0                  JAIR
972          0         1                     R
973          1         0             ADAMILTON
974          1         0               RODRIGO
975          0         1                  ROSA
976          0         1               SOLANGE
977          0         1             VERGULINA
978          1         0               RAYLSON
979          1         0             CRISTIANO
980          1         0                MARCIO
981          0         1                     J
982          0         1                SANDRA
983          0         1               GENILDA
984          1         0               EVERTON
985          1         0              HAMILTON
986          1         0               ROSINEI
987          1         0                  ALEX
988          1         0                SERGIO
989          0         1              BENEDITO
990          0         1              TARCILIA
991          1         0              AUDENAER
992          1         0                SABINO
993          1         0                ODINEY
994          1         0                Marcos
995          1         0                  LUIZ
996          1         0                 MASSA
997          1         0               OLDINEI
998          1         0                Abilio
999          1         0              Euclides

[1000 rows x 3 columns]

In [131]:
############# CountVectorizer ##################

df['PrimeiroNomeNoAccents'] = df['PrimeiroNomeNoAccents'].apply(lambda x: x.lower())
X = df['PrimeiroNomeNoAccents'].apply(lambda x: x.lower())

X

0        benedito
1      secretario
2            luiz
3          daniel
4          marcos
5            adao
6          waldir
7           sonia
8          marcos
9          keviny
10        valdeir
11           leni
12           luis
13        eugenio
14          celia
15           ilma
16         carlos
17          diego
18      neusalina
19        evelini
20         carlos
21         odemir
22        josenil
23       adeilton
24       benjamin
25       edmilson
26          edson
27       anderson
28         flavio
29           joao
          ...
970           ana
971          jair
972             r
973     adamilton
974       rodrigo
975          rosa
976       solange
977     vergulina
978       raylson
979     cristiano
980        marcio
981             j
982        sandra
983       genilda
984       everton
985      hamilton
986       rosinei
987          alex
988        sergio
989      benedito
990      tarcilia
991      audenaer
992        sabino
993        odiney
994        marcos
995          luiz
996         massa
997       oldinei
998        abilio
999      euclides
Name: PrimeiroNomeNoAccents, Length: 1000, dtype: object

In [155]:

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer(analyzer='char')
count_vect.fit_transform(X)
v2 = count_vect.vocabulary_

df['hash'] = X
df['hash'] = df['hash'].map(v2)
pd.concat([df[df['hash'].isna()][:5], df[df['hash'].notna()][:5]])

     Masculino  Feminino PrimeiroNomeNoAccents  hash
0            1         0              benedito   NaN
1            1         0            secretario   NaN
2            1         0                  luiz   NaN
3            1         0                daniel   NaN
4            1         0                marcos   NaN
46           0         1                     a   0.0
54           0         1                     j   9.0
155          0         1                     g   6.0
181          0         1                     r  17.0
221          0         1                     r  17.0

In [119]:
df['Sounde'] = df.apply(lambda row: soundex(row['PrimeiroNomeNoAccents']), axis=1)

In [120]:
df[df['Masculino'] == df['Feminino']]

Empty DataFrame
Columns: [Masculino, Feminino, PrimeiroNomeNoAccents, hash, Sounde]
Index: []

In [4]:
df['SoundexIndice0'] = df[df['Sounde'].notna()].apply(lambda row: ord(row['Sounde'][0:1]), axis=1)
df['SoundexIndice1'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][1:2]), axis=1)
df['SoundexIndice2'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][2:3]), axis=1)
df['SoundexIndice3'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][3:4]), axis=1)

In [5]:
df['Leng'] = df.apply(lambda row: len(row['PrimeiroNomeNoAccents']), axis=1)

In [6]:
for i in range(0, 10):
    df['LetraIndice' + str(i)] = df.apply(lambda row: getascii(row, i), axis=1)
    print('ok {0}'.format(i))

ok 0
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9

In [7]:
def getascii(row, indice):
    c = row['PrimeiroNomeNoAccents'][indice:indice+1]
    if(len(c) == 0):
        return np.nan
    return ord(c)

In [8]:
mean = df['LetraIndice1'].mean()
#df_backup = df
s = df[df['LetraIndice1'].isna()]['LetraIndice1']


values = {
    'LetraIndice1': df['LetraIndice1'].mean(), 
    'LetraIndice2': df['LetraIndice2'].mean(), 
    'LetraIndice3': df['LetraIndice3'].mean(), 
    'LetraIndice4': df['LetraIndice4'].mean(), 
    'LetraIndice5': df['LetraIndice5'].mean(), 
    'LetraIndice6': df['LetraIndice6'].mean(), 
    'LetraIndice7': df['LetraIndice7'].mean(), 
    'LetraIndice8': df['LetraIndice8'].mean(), 
    'LetraIndice9': df['LetraIndice9'].mean(), 
}

df = df.fillna(value=values)
df_Mean = pd.DataFrame(values, index=[0])
df_Mean.to_csv("mediaLetras.csv", index=False)

In [9]:
df.drop(['PrimeiroNomeNoAccents', 'Sounde'], axis=1)

,Masculino,Feminino,SoundexIndice0,SoundexIndice1,SoundexIndice2,SoundexIndice3,Leng,LetraIndice0,LetraIndice1,LetraIndice2,LetraIndice3,LetraIndice4,LetraIndice5,LetraIndice6,LetraIndice7,LetraIndice8,LetraIndice9
0,1,0,98,5,3,0,8,66,69.0,78.0,69.0,68.000000,73.00000,84.000000,79.000000,81.989951,80.279271
1,1,0,115,2,6,3,10,83,101.0,99.0,114.0,101.000000,116.00000,97.000000,114.000000,105.000000,111.000000
2,1,0,108,2,0,0,4,76,85.0,73.0,90.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
3,1,0,100,5,4,0,6,68,65.0,78.0,73.0,69.000000,76.00000,82.386687,81.648221,81.989951,80.279271
4,1,0,109,6,2,0,6,77,65.0,82.0,67.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
5,1,0,97,3,0,0,4,65,68.0,65.0,79.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
6,1,0,119,4,3,6,6,87,65.0,76.0,68.0,73.000000,82.00000,82.386687,81.648221,81.989951,80.279271
7,0,1,115,5,0,0,5,83,111.0,110.0,105.0,97.000000,82.58499,82.386687,81.648221,81.989951,80.279271
8,1,0,109,6,2,0,6,77,65.0,82.0,67.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
9,0,1,107,1,5,0,6,75,101.0,118.0,105.0,110.000000,121.00000,82.386687,81.648221,81.989951,80.279271
10,1,0,118,4,3,6,7,86,97.0,108.0,100.0,101.000000,105.00000,114.000000,81.648221,81.989951,80.279271
11,0,1,108,5,0,0,4,76,69.0,78.0,73.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
12,1,0,108,2,0,0,4,76,85.0,73.0,83.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
13,1,0,101,2,5,0,7,69,85.0,71.0,69.0,78.000000,73.00000,79.000000,81.648221,81.989951,80.279271
14,0,1,99,4,0,0,5,67,69.0,76.0,73.0,65.000000,82.58499,82.386687,81.648221,81.989951,80.279271
15,0,1,105,4,5,0,4,73,108.0,109.0,97.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
16,1,0,99,6,4,2,6,67,65.0,82.0,76.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
17,1,0,100,2,0,0,5,68,105.0,101.0,103.0,111.000000,82.58499,82.386687,81.648221,81.989951,80.279271
18,0,1,110,2,4,5,9,78,69.0,85.0,83.0,65.000000,76.00000,73.000000,78.000000,65.000000,80.279271
19,0,1,101,1,4,5,7,69,118.0,101.0,108.0,105.000000,110.00000,105.000000,81.648221,81.989951,80.279271
20,1,0,99,6,4,2,6,67,65.0,82.0,76.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
21,1,0,111,3,5,6,6,79,100.0,101.0,109.0,105.000000,114.00000,82.386687,81.648221,81.989951,80.279271
22,1,0,106,2,5,4,7,74,79.0,83.0,69.0,78.000000,73.00000,76.000000,81.648221,81.989951,80.279271
23,1,0,97,3,4,3,8,65,100.0,101.0,105.0,108.000000,116.00000,111.000000,110.000000,81.989951,80.279271
24,1,0,98,5,2,5,8,66,101.0,110.0,106.0,97.000000,109.00000,105.000000,110.000000,81.989951,80.279271
25,1,0,101,3,5,4,8,69,68.0,77.0,73.0,76.000000,83.00000,79.000000,78.000000,81.989951,80.279271
26,1,0,101,3,2,5,5,69,68.0,83.0,79.0,78.000000,82.58499,82.386687,81.648221,81.989951,80.279271
27,1,0,97,5,3,6,8,65,110.0,100.0,101.0,114.000000,115.00000,111.000000,110.000000,81.989951,80.279271
28,1,0,102,4,1,0,6,70,76.0,65.0,86.0,73.000000,79.00000,82.386687,81.648221,81.989951,80.279271
29,1,0,106,0,0,0,4,74,111.0,97.0,111.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,0,1,118,5,2,0,7,86,97.0,110.0,101.0,115.000000,115.00000,97.000000,81.648221,81.989951,80.279271
999971,1,0,106,2,0,0,4,74,79.0,83.0,69.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
999972,0,1,101,3,4,2,8,69,100.0,105.0,108.0,101.000000,117.00000,122.000000,97.000000,81.989951,80.279271
999973,0,1,110,3,0,0,5,78,69.0,73.0,68.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999974,0,1,106,2,4,5,9,74,65.0,81.0,85.0,69.000000,76.00000,73.000000,78.000000,69.000000,80.279271
999975,0,1,99,4,5,6,6,67,108.0,101.0,109.0,105.000000,114.00000,82.386687,81.648221,81.989951,80.279271
999976,0,1,114,2,5,0,6,82,69.0,71.0,73.0,78.000000,65.00000,82.386687,81.648221,81.989951,80.279271
999977,0,1,99,4,5,2,8,67,76.0,69.0,79.0,78.000000,73.00000,67.000000,69.000000,81.989951,80.279271
999978,1,0,114,2,6,0,7,82,111.0,103.0,101.0,114.000000,105.00000,111.000000,81.648221,81.989951,80.279271
999979,1,0,97,4,2,3,7,65,108.0,99.0,105.0,100.000000,101.00000,115.000000,81.648221,81.989951,80.279271
999980,0,1,99,4,5,2,8,67,76.0,69.0,79.0,78.000000,73.00000,67.000000,69.000000,81.989951,80.279271
999981,0,1,114,2,5,4,9,82,111.0,115.0,101.0,110.000000,105.00000,108.000000,100.000000,97.000000,80.279271
999982,1,0,111,1,3,0,6,79,118.0,105.0,100.0,105.000000,111.00000,82.386687,81.648221,81.989951,80.279271
999983,1,0,106,6,2,0,5,74,69.0,82.0,71.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999984,0,1,106,3,0,0,6,74,117.0,100.0,105.0,116.000000,101.00000,82.386687,81.648221,81.989951,80.279271
999985,0,1,105,6,5,0,5,73,82.0,69.0,78.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999986,1,0,108,2,0,0,4,76,85.0,73.0,90.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
999987,0,1,97,4,5,2,9,65,108.0,109.0,101.0,122.000000,105.00000,110.000000,100.000000,97.000000,80.279271
999988,1,0,114,5,1,4,9,82,79.0,78.0,73.0,86.000000,65.00000,76.000000,68.000000,79.000000,80.279271
999989,0,1,101,4,5,0,6,69,76.0,79.0,73.0,78.000000,65.00000,82.386687,81.648221,81.989951,80.279271
999990,1,0,101,2,1,4,7,69,115.0,112.0,111.0,108.000000,105.00000,111.000000,81.648221,81.989951,80.279271
999991,1,0,103,6,2,5,8,71,114.0,97.0,115.0,105.000000,109.00000,97.000000,114.000000,81.989951,80.279271
999992,1,0,109,5,4,0,6,77,65.0,78.0,79.0,69.000000,76.00000,82.386687,81.648221,81.989951,80.279271
999993,0,1,100,1,6,0,6,68,101.0,98.0,111.0,114.000000,97.00000,82.386687,81.648221,81.989951,80.279271
999994,1,0,101,1,6,4,8,69,118.0,101.0,114.0,97.000000,108.00000,100.000000,111.000000,81.989951,80.279271
999995,0,1,109,6,4,2,8,77,97.0,114.0,105.0,108.000000,117.00000,99.000000,105.000000,81.989951,80.279271
999996,1,0,104,5,4,3,8,72,65.0,77.0,73.0,76.000000,84.00000,79.000000,78.000000,81.989951,80.279271
999997,0,1,101,1,5,6,6,69,86.0,65.0,78.0,73.000000,82.00000,82.386687,81.648221,81.989951,80.279271
999998,0,1,109,6,0,0,5,77,65.0,82.0,73.0,65.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999999,1,0,101,1,6,3,7,69,86.0,69.0,82.0,84.000000,79.00000,78.000000,81.648221,81.989951,80.279271

In [10]:
df

,Masculino,Feminino,PrimeiroNomeNoAccents,Sounde,SoundexIndice0,SoundexIndice1,SoundexIndice2,SoundexIndice3,Leng,LetraIndice0,LetraIndice1,LetraIndice2,LetraIndice3,LetraIndice4,LetraIndice5,LetraIndice6,LetraIndice7,LetraIndice8,LetraIndice9
0,1,0,BENEDITO,b530,98,5,3,0,8,66,69.0,78.0,69.0,68.000000,73.00000,84.000000,79.000000,81.989951,80.279271
1,1,0,Secretario,s263,115,2,6,3,10,83,101.0,99.0,114.0,101.000000,116.00000,97.000000,114.000000,105.000000,111.000000
2,1,0,LUIZ,l200,108,2,0,0,4,76,85.0,73.0,90.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
3,1,0,DANIEL,d540,100,5,4,0,6,68,65.0,78.0,73.0,69.000000,76.00000,82.386687,81.648221,81.989951,80.279271
4,1,0,MARCOS,m620,109,6,2,0,6,77,65.0,82.0,67.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
5,1,0,ADAO,a300,97,3,0,0,4,65,68.0,65.0,79.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
6,1,0,WALDIR,w436,119,4,3,6,6,87,65.0,76.0,68.0,73.000000,82.00000,82.386687,81.648221,81.989951,80.279271
7,0,1,Sonia,s500,115,5,0,0,5,83,111.0,110.0,105.0,97.000000,82.58499,82.386687,81.648221,81.989951,80.279271
8,1,0,MARCOS,m620,109,6,2,0,6,77,65.0,82.0,67.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
9,0,1,Keviny,k150,107,1,5,0,6,75,101.0,118.0,105.0,110.000000,121.00000,82.386687,81.648221,81.989951,80.279271
10,1,0,Valdeir,v436,118,4,3,6,7,86,97.0,108.0,100.0,101.000000,105.00000,114.000000,81.648221,81.989951,80.279271
11,0,1,LENI,l500,108,5,0,0,4,76,69.0,78.0,73.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
12,1,0,LUIS,l200,108,2,0,0,4,76,85.0,73.0,83.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
13,1,0,EUGENIO,e250,101,2,5,0,7,69,85.0,71.0,69.0,78.000000,73.00000,79.000000,81.648221,81.989951,80.279271
14,0,1,CELIA,c400,99,4,0,0,5,67,69.0,76.0,73.0,65.000000,82.58499,82.386687,81.648221,81.989951,80.279271
15,0,1,Ilma,i450,105,4,5,0,4,73,108.0,109.0,97.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
16,1,0,CARLOS,c642,99,6,4,2,6,67,65.0,82.0,76.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
17,1,0,Diego,d200,100,2,0,0,5,68,105.0,101.0,103.0,111.000000,82.58499,82.386687,81.648221,81.989951,80.279271
18,0,1,NEUSALINA,n245,110,2,4,5,9,78,69.0,85.0,83.0,65.000000,76.00000,73.000000,78.000000,65.000000,80.279271
19,0,1,Evelini,e145,101,1,4,5,7,69,118.0,101.0,108.0,105.000000,110.00000,105.000000,81.648221,81.989951,80.279271
20,1,0,CARLOS,c642,99,6,4,2,6,67,65.0,82.0,76.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
21,1,0,Odemir,o356,111,3,5,6,6,79,100.0,101.0,109.0,105.000000,114.00000,82.386687,81.648221,81.989951,80.279271
22,1,0,JOSENIL,j254,106,2,5,4,7,74,79.0,83.0,69.0,78.000000,73.00000,76.000000,81.648221,81.989951,80.279271
23,1,0,Adeilton,a343,97,3,4,3,8,65,100.0,101.0,105.0,108.000000,116.00000,111.000000,110.000000,81.989951,80.279271
24,1,0,Benjamin,b525,98,5,2,5,8,66,101.0,110.0,106.0,97.000000,109.00000,105.000000,110.000000,81.989951,80.279271
25,1,0,EDMILSON,e354,101,3,5,4,8,69,68.0,77.0,73.0,76.000000,83.00000,79.000000,78.000000,81.989951,80.279271
26,1,0,EDSON,e325,101,3,2,5,5,69,68.0,83.0,79.0,78.000000,82.58499,82.386687,81.648221,81.989951,80.279271
27,1,0,Anderson,a536,97,5,3,6,8,65,110.0,100.0,101.0,114.000000,115.00000,111.000000,110.000000,81.989951,80.279271
28,1,0,FLAVIO,f410,102,4,1,0,6,70,76.0,65.0,86.0,73.000000,79.00000,82.386687,81.648221,81.989951,80.279271
29,1,0,Joao,j000,106,0,0,0,4,74,111.0,97.0,111.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,0,1,Vanessa,v520,118,5,2,0,7,86,97.0,110.0,101.0,115.000000,115.00000,97.000000,81.648221,81.989951,80.279271
999971,1,0,JOSE,j200,106,2,0,0,4,74,79.0,83.0,69.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
999972,0,1,Edileuza,e342,101,3,4,2,8,69,100.0,105.0,108.0,101.000000,117.00000,122.000000,97.000000,81.989951,80.279271
999973,0,1,NEIDE,n300,110,3,0,0,5,78,69.0,73.0,68.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999974,0,1,JAQUELINE,j245,106,2,4,5,9,74,65.0,81.0,85.0,69.000000,76.00000,73.000000,78.000000,69.000000,80.279271
999975,0,1,Clemir,c456,99,4,5,6,6,67,108.0,101.0,109.0,105.000000,114.00000,82.386687,81.648221,81.989951,80.279271
999976,0,1,REGINA,r250,114,2,5,0,6,82,69.0,71.0,73.0,78.000000,65.00000,82.386687,81.648221,81.989951,80.279271
999977,0,1,CLEONICE,c452,99,4,5,2,8,67,76.0,69.0,79.0,78.000000,73.00000,67.000000,69.000000,81.989951,80.279271
999978,1,0,Rogerio,r260,114,2,6,0,7,82,111.0,103.0,101.0,114.000000,105.00000,111.000000,81.648221,81.989951,80.279271
999979,1,0,Alcides,a423,97,4,2,3,7,65,108.0,99.0,105.0,100.000000,101.00000,115.000000,81.648221,81.989951,80.279271
999980,0,1,CLEONICE,c452,99,4,5,2,8,67,76.0,69.0,79.0,78.000000,73.00000,67.000000,69.000000,81.989951,80.279271
999981,0,1,Rosenilda,r254,114,2,5,4,9,82,111.0,115.0,101.0,110.000000,105.00000,108.000000,100.000000,97.000000,80.279271
999982,1,0,Ovidio,o130,111,1,3,0,6,79,118.0,105.0,100.0,105.000000,111.00000,82.386687,81.648221,81.989951,80.279271
999983,1,0,JERGE,j620,106,6,2,0,5,74,69.0,82.0,71.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999984,0,1,Judite,j300,106,3,0,0,6,74,117.0,100.0,105.0,116.000000,101.00000,82.386687,81.648221,81.989951,80.279271
999985,0,1,IRENE,i650,105,6,5,0,5,73,82.0,69.0,78.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999986,1,0,LUIZ,l200,108,2,0,0,4,76,85.0,73.0,90.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
999987,0,1,Almezinda,a452,97,4,5,2,9,65,108.0,109.0,101.0,122.000000,105.00000,110.000000,100.000000,97.000000,80.279271
999988,1,0,RONIVALDO,r514,114,5,1,4,9,82,79.0,78.0,73.0,86.000000,65.00000,76.000000,68.000000,79.000000,80.279271
999989,0,1,ELOINA,e450,101,4,5,0,6,69,76.0,79.0,73.0,78.000000,65.00000,82.386687,81.648221,81.989951,80.279271
999990,1,0,Espolio,e214,101,2,1,4,7,69,115.0,112.0,111.0,108.000000,105.00000,111.000000,81.648221,81.989951,80.279271
999991,1,0,Grasimar,g625,103,6,2,5,8,71,114.0,97.0,115.0,105.000000,109.00000,97.000000,114.000000,81.989951,80.279271
999992,1,0,MANOEL,m540,109,5,4,0,6,77,65.0,78.0,79.0,69.000000,76.00000,82.386687,81.648221,81.989951,80.279271
999993,0,1,Debora,d160,100,1,6,0,6,68,101.0,98.0,111.0,114.000000,97.00000,82.386687,81.648221,81.989951,80.279271
999994,1,0,Everaldo,e164,101,1,6,4,8,69,118.0,101.0,114.0,97.000000,108.00000,100.000000,111.000000,81.989951,80.279271
999995,0,1,Mariluci,m642,109,6,4,2,8,77,97.0,114.0,105.0,108.000000,117.00000,99.000000,105.000000,81.989951,80.279271
999996,1,0,HAMILTON,h543,104,5,4,3,8,72,65.0,77.0,73.0,76.000000,84.00000,79.000000,78.000000,81.989951,80.279271
999997,0,1,EVANIR,e156,101,1,5,6,6,69,86.0,65.0,78.0,73.000000,82.00000,82.386687,81.648221,81.989951,80.279271
999998,0,1,MARIA,m600,109,6,0,0,5,77,65.0,82.0,73.0,65.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999999,1,0,EVERTON,e163,101,1,6,3,7,69,86.0,69.0,82.0,84.000000,79.00000,78.000000,81.648221,81.989951,80.279271

In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = df.drop(['Masculino', 'Feminino', 'PrimeiroNomeNoAccents', 'Sounde'], axis=1)
y = df.loc[:, 'Masculino']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.33, random_state=7)

X
#est = RandomForestClassifier(n_estimators = 40).fit(X, y)
#est.score(X, y)

#est = reg

,SoundexIndice0,SoundexIndice1,SoundexIndice2,SoundexIndice3,Leng,LetraIndice0,LetraIndice1,LetraIndice2,LetraIndice3,LetraIndice4,LetraIndice5,LetraIndice6,LetraIndice7,LetraIndice8,LetraIndice9
0,98,5,3,0,8,66,69.0,78.0,69.0,68.000000,73.00000,84.000000,79.000000,81.989951,80.279271
1,115,2,6,3,10,83,101.0,99.0,114.0,101.000000,116.00000,97.000000,114.000000,105.000000,111.000000
2,108,2,0,0,4,76,85.0,73.0,90.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
3,100,5,4,0,6,68,65.0,78.0,73.0,69.000000,76.00000,82.386687,81.648221,81.989951,80.279271
4,109,6,2,0,6,77,65.0,82.0,67.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
5,97,3,0,0,4,65,68.0,65.0,79.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
6,119,4,3,6,6,87,65.0,76.0,68.0,73.000000,82.00000,82.386687,81.648221,81.989951,80.279271
7,115,5,0,0,5,83,111.0,110.0,105.0,97.000000,82.58499,82.386687,81.648221,81.989951,80.279271
8,109,6,2,0,6,77,65.0,82.0,67.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
9,107,1,5,0,6,75,101.0,118.0,105.0,110.000000,121.00000,82.386687,81.648221,81.989951,80.279271
10,118,4,3,6,7,86,97.0,108.0,100.0,101.000000,105.00000,114.000000,81.648221,81.989951,80.279271
11,108,5,0,0,4,76,69.0,78.0,73.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
12,108,2,0,0,4,76,85.0,73.0,83.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
13,101,2,5,0,7,69,85.0,71.0,69.0,78.000000,73.00000,79.000000,81.648221,81.989951,80.279271
14,99,4,0,0,5,67,69.0,76.0,73.0,65.000000,82.58499,82.386687,81.648221,81.989951,80.279271
15,105,4,5,0,4,73,108.0,109.0,97.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
16,99,6,4,2,6,67,65.0,82.0,76.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
17,100,2,0,0,5,68,105.0,101.0,103.0,111.000000,82.58499,82.386687,81.648221,81.989951,80.279271
18,110,2,4,5,9,78,69.0,85.0,83.0,65.000000,76.00000,73.000000,78.000000,65.000000,80.279271
19,101,1,4,5,7,69,118.0,101.0,108.0,105.000000,110.00000,105.000000,81.648221,81.989951,80.279271
20,99,6,4,2,6,67,65.0,82.0,76.0,79.000000,83.00000,82.386687,81.648221,81.989951,80.279271
21,111,3,5,6,6,79,100.0,101.0,109.0,105.000000,114.00000,82.386687,81.648221,81.989951,80.279271
22,106,2,5,4,7,74,79.0,83.0,69.0,78.000000,73.00000,76.000000,81.648221,81.989951,80.279271
23,97,3,4,3,8,65,100.0,101.0,105.0,108.000000,116.00000,111.000000,110.000000,81.989951,80.279271
24,98,5,2,5,8,66,101.0,110.0,106.0,97.000000,109.00000,105.000000,110.000000,81.989951,80.279271
25,101,3,5,4,8,69,68.0,77.0,73.0,76.000000,83.00000,79.000000,78.000000,81.989951,80.279271
26,101,3,2,5,5,69,68.0,83.0,79.0,78.000000,82.58499,82.386687,81.648221,81.989951,80.279271
27,97,5,3,6,8,65,110.0,100.0,101.0,114.000000,115.00000,111.000000,110.000000,81.989951,80.279271
28,102,4,1,0,6,70,76.0,65.0,86.0,73.000000,79.00000,82.386687,81.648221,81.989951,80.279271
29,106,0,0,0,4,74,111.0,97.0,111.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999970,118,5,2,0,7,86,97.0,110.0,101.0,115.000000,115.00000,97.000000,81.648221,81.989951,80.279271
999971,106,2,0,0,4,74,79.0,83.0,69.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
999972,101,3,4,2,8,69,100.0,105.0,108.0,101.000000,117.00000,122.000000,97.000000,81.989951,80.279271
999973,110,3,0,0,5,78,69.0,73.0,68.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999974,106,2,4,5,9,74,65.0,81.0,85.0,69.000000,76.00000,73.000000,78.000000,69.000000,80.279271
999975,99,4,5,6,6,67,108.0,101.0,109.0,105.000000,114.00000,82.386687,81.648221,81.989951,80.279271
999976,114,2,5,0,6,82,69.0,71.0,73.0,78.000000,65.00000,82.386687,81.648221,81.989951,80.279271
999977,99,4,5,2,8,67,76.0,69.0,79.0,78.000000,73.00000,67.000000,69.000000,81.989951,80.279271
999978,114,2,6,0,7,82,111.0,103.0,101.0,114.000000,105.00000,111.000000,81.648221,81.989951,80.279271
999979,97,4,2,3,7,65,108.0,99.0,105.0,100.000000,101.00000,115.000000,81.648221,81.989951,80.279271
999980,99,4,5,2,8,67,76.0,69.0,79.0,78.000000,73.00000,67.000000,69.000000,81.989951,80.279271
999981,114,2,5,4,9,82,111.0,115.0,101.0,110.000000,105.00000,108.000000,100.000000,97.000000,80.279271
999982,111,1,3,0,6,79,118.0,105.0,100.0,105.000000,111.00000,82.386687,81.648221,81.989951,80.279271
999983,106,6,2,0,5,74,69.0,82.0,71.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999984,106,3,0,0,6,74,117.0,100.0,105.0,116.000000,101.00000,82.386687,81.648221,81.989951,80.279271
999985,105,6,5,0,5,73,82.0,69.0,78.0,69.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999986,108,2,0,0,4,76,85.0,73.0,90.0,81.513655,82.58499,82.386687,81.648221,81.989951,80.279271
999987,97,4,5,2,9,65,108.0,109.0,101.0,122.000000,105.00000,110.000000,100.000000,97.000000,80.279271
999988,114,5,1,4,9,82,79.0,78.0,73.0,86.000000,65.00000,76.000000,68.000000,79.000000,80.279271
999989,101,4,5,0,6,69,76.0,79.0,73.0,78.000000,65.00000,82.386687,81.648221,81.989951,80.279271
999990,101,2,1,4,7,69,115.0,112.0,111.0,108.000000,105.00000,111.000000,81.648221,81.989951,80.279271
999991,103,6,2,5,8,71,114.0,97.0,115.0,105.000000,109.00000,97.000000,114.000000,81.989951,80.279271
999992,109,5,4,0,6,77,65.0,78.0,79.0,69.000000,76.00000,82.386687,81.648221,81.989951,80.279271
999993,100,1,6,0,6,68,101.0,98.0,111.0,114.000000,97.00000,82.386687,81.648221,81.989951,80.279271
999994,101,1,6,4,8,69,118.0,101.0,114.0,97.000000,108.00000,100.000000,111.000000,81.989951,80.279271
999995,109,6,4,2,8,77,97.0,114.0,105.0,108.000000,117.00000,99.000000,105.000000,81.989951,80.279271
999996,104,5,4,3,8,72,65.0,77.0,73.0,76.000000,84.00000,79.000000,78.000000,81.989951,80.279271
999997,101,1,5,6,6,69,86.0,65.0,78.0,73.000000,82.00000,82.386687,81.648221,81.989951,80.279271
999998,109,6,0,0,5,77,65.0,82.0,73.0,65.000000,82.58499,82.386687,81.648221,81.989951,80.279271
999999,101,1,6,3,7,69,86.0,69.0,82.0,84.000000,79.00000,78.000000,81.648221,81.989951,80.279271

In [12]:
c = pd.concat([df.loc[:,'PrimeiroNomeNoAccents'], X], axis=1)

In [13]:
# TODO: Import 'make_scorer', 'DecisionTreeRegressor', and 'GridSearchCV'
from sklearn.metrics import make_scorer
from sklearn.tree import DecisionTreeRegressor 
from sklearn.model_selection import ShuffleSplit, GridSearchCV


# O fit_model(...) cria uma um estimador de árvore de decisão, faz o CV do parâmetro 'max_depth' de 1 a 10, depois faz um Grid Search CV, e retorna o grid.best_estimator_;
def fit_model(X, y):
    """ Performs grid search over the 'max_depth' parameter for a 
        decision tree regressor trained on the input data [X, y]. """
    
    # Create cross-validation sets from the training data
    # sklearn version 0.18: ShuffleSplit(n_splits=10, test_size=0.1, train_size=None, random_state=None)
    cv_sets = ShuffleSplit(n_splits=5, test_size = 0.20, random_state = 0)

    # TODO: Create a decision tree regressor object
    regressor = RandomForestClassifier()

    # TODO: Create a dictionary for the parameter 'max_depth' with a range from 1 to 10
    #params = {"n_estimators":[10, 20, 40, 80, 200]}

    param_grid = { 
        #'n_estimators': [200, 500, 2000],
        'n_estimators': [200],
        #'max_features': ['auto', 'sqrt', 'log2'],
        'max_depth' : [12,20],
        'max_depth' : [12],
        'criterion' :['gini', 'entropy']
        #'criterion' :['gini']
    }
    
    # TODO: Create the grid search object
    grid = GridSearchCV(regressor, param_grid, cv=cv_sets)

    # Fit the grid search object to the data to compute the optimal model
    grid = grid.fit(X, y)

    # Return the optimal model after fitting the data
    return grid.best_estimator_

In [14]:
param_grid = {
    'n_estimators': 200,
    'max_depth' : 12,
    'criterion' :'gini'
}


# Fit the training data to the model using grid search
#est = fit_model(X_train, y_train)
est = RandomForestClassifier(**param_grid)
est.fit(X, y)

print(est.get_params())

{'bootstrap': True, 'class_weight': None, 'criterion': 'gini', 'max_depth': 12, 'max_features': 'auto', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 200, 'n_jobs': 1, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

In [15]:
est.score(X, y)

0.934285771657879

In [16]:
est.score(X_test, y_test)

0.9338728634702655

In [17]:
est.score(X_train, y_train)

0.9344891443570216

In [18]:
import pickle
s = pickle.dumps(est)
clf2 = pickle.loads(s)
clf2.score(X_train, y_train)

0.9344891443570216

In [19]:
from sklearn.externals import joblib

In [20]:
joblib.dump(est, 'modelo_RandomForest_1milhao.pkl', compress=9)

['modelo_RandomForest_1milhao.pkl']

In [6]:
categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']

from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)

In [7]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [32]:
twenty_train.target[:10]

array([1, 1, 3, 3, 3, 3, 3, 2, 2, 2], dtype=int64)

In [34]:
for t in twenty_train.target[:10]:
    print(twenty_train.target_names[t])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(twenty_train.data)
X_train_counts.shape
#X_train_counts.toarray()[0]

(2257, 35788)

In [123]:
import numpy as np

v = count_vect.vocabulary_
n = np.array(v)
v

{'from': 14887,
 'sd345': 29022,
 'city': 8696,
 'ac': 4017,
 'uk': 33256,
 'michael': 21661,
 'collier': 9031,
 'subject': 31077,
 'converting': 9805,
 'images': 17366,
 'to': 32493,
 'hp': 16916,
 'laserjet': 19780,
 'iii': 17302,
 'nntp': 23122,
 'posting': 25663,
 'host': 16881,
 'hampton': 16082,
 'organization': 23915,
 'the': 32142,
 'university': 33597,
 'lines': 20253,
 '14': 587,
 'does': 12051,
 'anyone': 5201,
 'know': 19458,
 'of': 23610,
 'good': 15576,
 'way': 34755,
 'standard': 30623,
 'pc': 24651,
 'application': 5285,
 'pd': 24677,
 'utility': 33915,
 'convert': 9801,
 'tif': 32391,
 'img': 17389,
 'tga': 32116,
 'files': 14281,
 'into': 18268,
 'format': 14676,
 'we': 34775,
 'would': 35312,
 'also': 4808,
 'like': 20198,
 'do': 12014,
 'same': 28619,
 'hpgl': 16927,
 'plotter': 25361,
 'please': 25337,
 'email': 12833,
 'any': 5195,
 'response': 27836,
 'is': 18474,
 'this': 32270,
 'correct': 9932,
 'group': 15837,
 'thanks': 32135,
 'in': 17556,
 'advance': 4378,
 'programmer': 26175,
 'computer': 9338,
 'unit': 33572,
 'tel': 31915,
 '071': 177,
 '477': 2326,
 '8000': 3062,
 'x3769': 35416,
 'london': 20459,
 'fax': 14085,
 '8565': 3166,
 'ec1v': 12541,
 '0hb': 230,
 'ani': 5046,
 'ms': 22366,
 'uky': 33267,
 'edu': 12626,
 'aniruddha': 5062,
 'deglurkar': 11001,
 'help': 16418,
 'splitting': 30464,
 'trimming': 32915,
 'region': 27378,
 'along': 4788,
 'mesh': 21550,
 'kentucky': 19254,
 'dept': 11193,
 'math': 21153,
 'sciences': 28899,
 '28': 1731,
 'hi': 16550,
 'have': 16254,
 'problem': 26093,
 'hope': 16833,
 'some': 30173,
 'gurus': 15949,
 'can': 7766,
 'me': 21322,
 'solve': 30164,
 'background': 6031,
 'rectangular': 27238,
 'uv': 33949,
 'domain': 12075,
 'mapping': 20985,
 '3d': 2148,
 'bezier': 6574,
 'patch': 24567,
 '2d': 1858,
 'area': 5411,
 'which': 34954,
 'inside': 18016,
 'loop': 20480,
 'had': 16014,
 'be': 6298,
 'rendered': 27582,
 'set': 29313,
 'curve': 10471,
 'segments': 29147,
 'for': 14601,
 'sake': 28580,
 'notation': 23256,
 'made': 20770,
 'up': 33773,
 'cells': 8153,
 'my': 22541,
 'has': 16216,
 'split': 30462,
 'individual': 17716,
 'smaller': 29976,
 'bounded': 7085,
 'by': 7505,
 'if': 17268,
 'cell': 8150,
 'wholly': 34992,
 'then': 32164,
 'it': 18551,
 'output': 24079,
 'as': 5549,
 'whole': 34987,
 'else': 12817,
 'trivially': 32945,
 'rejected': 27438,
 'body': 6939,
 'how': 16908,
 'thiss': 32271,
 'done': 12103,
 'or': 23870,
 'there': 32202,
 'algo': 4687,
 'somewhere': 30194,
 'doing': 12065,
 'appreciated': 5304,
 'get': 15319,
 'irritated': 18465,
 'human': 16999,
 'stay': 30701,
 'cool': 9839,
 'divine': 11944,
 'djohnson': 11966,
 'cs': 10324,
 'ucsd': 33216,
 'darin': 10667,
 'johnson': 18893,
 're': 27031,
 'harrassed': 16194,
 'at': 5698,
 'work': 35255,
 'could': 9992,
 'use': 33858,
 'prayers': 25765,
 'cse': 10339,
 'san': 28631,
 'diego': 11499,
 '63': 2648,
 'well': 34866,
 'll': 20373,
 'but': 7480,
 'may': 21209,
 'apply': 5289,
 'other': 24020,
 'people': 24784,
 'so': 30068,
 'post': 25646,
 've': 34120,
 'been': 6358,
 'working': 35264,
 'company': 9191,
 'eight': 12703,
 'years': 35587,
 'various': 34083,
 'engineering': 13051,
 'jobs': 18863,
 'female': 14166,
 'yesterday': 35603,
 'counted': 10004,
 'and': 4992,
 'realized': 27084,
 'that': 32139,
 'on': 23733,
 'seven': 29333,
 'different': 11520,
 'occasions': 23548,
 'sexually': 29352,
 'dreaded': 12231,
 'coming': 9110,
 'back': 6024,
 'today': 32506,
 'what': 34923,
 'boss': 7056,
 'comes': 9098,
 'ask': 5578,
 'kind': 19370,
 'question': 26709,
 'your': 35648,
 'should': 29578,
 'person': 24895,
 'bring': 7231,
 'these': 32221,
 'problems': 26097,
 'he': 16302,
 'she': 29455,
 'not': 23250,
 'seem': 29130,
 'take': 31710,
 'action': 4194,
 'keep': 19210,
 'going': 15545,
 'higher': 16573,
 'sexual': 29350,
 'harrassment': 16195,
 'need': 22774,
 'tolerated': 32530,
 'an': 4938,
 'enormous': 13089,
 'emotional': 12899,
 'support': 31364,
 'discuss': 11723,
 'with': 35157,
 'someone': 30180,
 'they': 32233,
 'are': 5410,
 'trying': 32997,
 'something': 30187,
 'about': 3958,
 'you': 35638,
 'feel': 14135,
 'perhaps': 24827,
 'personnel': 24908,
 'department': 11159,
 'while': 34956,
 'preserving': 25924,
 'privacy': 26060,
 'most': 22270,
 'companies': 9188,
 'will': 35057,
 'want': 34660,
 'deal': 10797,
 'because': 6333,
 'constant': 9614,
 'anxiety': 5193,
 'seriously': 29286,
 'affect': 4431,
 'effectively': 12659,
 'employees': 12924,
 'their': 32152,
 'unclear': 33374,
 'letter': 20054,
 'inconceivable': 17622,
 'management': 20906,
 'remains': 27528,
 'ignorant': 17283,
 'employee': 12923,
 'strife': 30973,
 'even': 13491,
 'after': 4471,
 'miracle': 21859,
 'notice': 23268,
 'manager': 20907,
 'did': 11493,
 'attention': 5783,
 'ups': 33807,
 'indeed': 17666,
 'ignore': 17287,
 'entire': 13132,
 'state': 30673,
 'agency': 4496,
 'willing': 35073,
 'fight': 14265,
 'check': 8380,
 'lawyer': 19852,
 'women': 35216,
 'resource': 27816,
 'center': 8159,
 'etc': 13400,
 'find': 14309,
 'out': 24052,
 'paster': 24555,
 'priest': 26010,
 'husband': 17055,
 'judgemental': 19017,
 'supportive': 31370,
 'comforting': 9106,
 'lot': 20517,
 'healing': 16325,
 'returned': 27926,
 '11': 336,
 '25': 1632,
 'only': 23757,
 'ever': 13503,
 'single': 29769,
 'already': 4805,
 'left': 19951,
 'lunch': 20631,
 '15': 677,
 'no': 23123,
 'one': 23741,
 'bothered': 7065,
 'call': 7714,
 'building': 7391,
 'though': 32297,
 'number': 23363,
 'was': 34703,
 'posted': 25654,
 'happens': 16136,
 'honest': 16803,
 'believe': 6430,
 'due': 12354,
 'gross': 15827,
 'insensitivity': 18009,
 'feelings': 14138,
 'through': 32332,
 'offices': 23636,
 'tend': 31978,
 'more': 22215,
 'insensitive': 18008,
 'than': 32131,
 'normally': 23215,
 'maybe': 21212,
 'hustle': 17068,
 'stress': 30954,
 'happen': 16131,
 'often': 23654,
 'didn': 11495,
 'realize': 27083,
 'car': 7860,
 'broken': 7265,
 'come': 9093,
 'wonder': 35218,
 'why': 35006,
 'go': 15511,
 'make': 20862,
 'stop': 30874,
 'being': 6412,
 'angry': 5041,
 'ignored': 17288,
 'laugh': 19819,
 'once': 23736,
 'went': 34876,
 'off': 23614,
 'without': 35168,
 'our': 24046,
 'who': 34982,
 'paying': 24636,
 'reason': 27103,
 'mr': 22356,
 'moderator': 22069,
 'allows': 4766,
 'latest': 19802,
 'indulgence': 17737,
 'turn': 33078,
 'signs': 29690,
 'age': 4492,
 'closing': 8860,
 'don': 12096,
 'let': 20048,
 'hateful': 16235,
 'actions': 4195,
 'harm': 16179,
 'still': 30808,
 'playground': 25324,
 'bully': 7413,
 'enjoy': 13068,
 'seeing': 29124,
 'hurt': 17050,
 'cause': 8034,
 'accept': 4039,
 'opinions': 23815,
 'imbecile': 17384,
 'worthless': 35306,
 'much': 22403,
 'wiser': 35145,
 'hold': 16743,
 'great': 15743,
 'esteem': 13379,
 'luxury': 20663,
 'day': 10752,
 'bytes': 7517,
 'swap': 31497,
 's0612596': 28498,
 'rug': 28425,
 'nl': 23102,
 'zwart': 35780,
 'catholic': 8017,
 'church': 8609,
 'poland': 25461,
 'faculteit': 13921,
 'der': 11198,
 'letteren': 20056,
 'rijksuniversiteit': 28104,
 'groningen': 15824,
 '10': 242,
 'hello': 16413,
 'writing': 35351,
 'paper': 24382,
 'role': 28256,
 '1989': 1097,
 'tell': 31945,
 'fill': 14285,
 'recent': 27149,
 'books': 7008,
 'articles': 5530,
 'english': 13055,
 'german': 15305,
 'french': 14842,
 'important': 17508,
 'concerning': 9379,
 'abortion': 3954,
 'law': 19841,
 'religious': 27510,
 'education': 12629,
 'schools': 28877,
 'birth': 6726,
 'control': 9771,
 'relation': 27456,
 'government': 15618,
 'thanx': 32138,
 'masja': 21101,
 'stanly': 30638,
 'grok11': 15822,
 'columbiasc': 9067,
 'ncr': 22725,
 'com': 9072,
 'elder': 12731,
 'brother': 7280,
 'corp': 9925,
 'columbia': 9066,
 'sc': 28771,
 'article': 5529,
 'apr': 5340,
 '00': 0,
 '57': 2521,
 '41': 2203,
 '1993': 1102,
 '28246': 1742,
 'athos': 5730,
 'rutgers': 28473,
 'rexlex': 27997,
 'fnal': 14526,
 'gov': 15612,
 'writes': 35350,
 '01': 37,
 '56': 2513,
 '22824': 1540,
 'shrum': 29610,
 'hpfcso': 16926,
 'fc': 14095,
 'matt': 21176,
 '22': 1490,
 'therefore': 32205,
 'main': 20842,
 'highways': 16585,
 'many': 20978,
 'invite': 18363,
 'wedding': 34810,
 'feast': 14109,
 'hmmmmmm': 16703,
 'sounds': 30250,
 'theology': 32179,
 'christ': 8544,
 'odds': 23595,
 'am': 4852,
 'parable': 24395,
 'jesus': 18774,
 'tells': 31948,
 'kingdom': 19383,
 'heaven': 16358,
 'unto': 33741,
 'certain': 8197,
 'king': 19382,
 'marriage': 21060,
 'his': 16642,
 'son': 30199,
 'clothes': 8863,
 'were': 34879,
 'customary': 10481,
 'given': 15406,
 'those': 32295,
 'chose': 8525,
 'attend': 5777,
 'man': 20903,
 'refused': 27352,
 'wear': 34790,
 'equalivant': 13239,
 'righteousness': 28091,
 'when': 34935,
 'died': 11498,
 'sins': 29785,
 'provided': 26356,
 'decision': 10874,
 'put': 26570,
 'vbv': 34111,
 'lor': 20493,
 'eeap': 12639,
 'cwru': 10510,
 'virgilio': 34360,
 'dean': 10805,
 'velasco': 34151,
 'jr': 18983,
 'arrogance': 5512,
 'christians': 8559,
 'case': 7965,
 'western': 34896,
 'reserve': 27768,
 'univ': 33581,
 'cleveland': 8795,
 'ohio': 23662,
 'usa': 33848,
 '2073': 1396,
 'geneva': 15237,
 'hayesstw': 16277,
 'risc1': 28131,
 'unisa': 33569,
 'za': 35688,
 'steve': 30776,
 'hayes': 16276,
 'similar': 29715,
 'analogy': 4953,
 'might': 21732,
 'medical': 21386,
 'doctor': 12026,
 'believes': 6437,
 'blood': 6863,
 'transfusion': 32756,
 'necessary': 22765,
 'save': 28735,
 'life': 20167,
 'child': 8451,
 'whose': 34999,
 'parents': 24451,
 'jehovah': 18729,
 'witnesses': 35176,
 'conscientious': 9557,
 'objections': 23477,
 'efforts': 12669,
 'persuade': 24913,
 'them': 32160,
 'agree': 4529,
 'perceived': 24793,
 'arrogant': 5513,
 'precisely': 25794,
 'truth': 32989,
 'otherwise': 24026,
 'belief': 6426,
 'irrelevant': 18452,
 'here': 16482,
 'matters': 21179,
 'true': 32973,
 'seen': 29135,
 'foce': 14533,
 'beliefs': 6427,
 'carry': 7938,
 'step': 30747,
 'further': 15006,
 'doctors': 12028,
 'claim': 8713,
 'infallible': 17784,
 'generally': 15219,
 'admit': 4330,
 'conceivably': 9360,
 'wrong': 35358,
 'tranfusion': 32722,
 'all': 4720,
 'however': 16913,
 'enough': 13091,
 'confidence': 9461,
 'conviction': 9816,
 'genuine': 15261,
 'concern': 9377,
 'fallible': 13977,
 'beings': 6413,
 'must': 22509,
 'acknowledge': 4153,
 'possibility': 25640,
 'say': 28755,
 'such': 31180,
 'doubts': 12166,
 'reasonable': 27105,
 'stand': 30621,
 'convictions': 9817,
 'electrical': 12746,
 'eng': 13037,
 'applied': 5287,
 'physics': 25121,
 'graduate': 15653,
 'student': 31031,
 'roboticist': 28207,
 'training': 32709,
 'wannabee': 34657,
 'bullwinkle': 7412,
 'intimidating': 18267,
 'referee': 27307,
 'very': 34229,
 'doesn': 12052,
 'look': 20470,
 'jewish': 18779,
 'carpenter': 7928,
 'jodfishe': 18866,
 'silver': 29706,
 'ucs': 33213,
 'indiana': 17687,
 'joseph': 18929,
 'dale': 10604,
 'fisher': 14363,
 'anger': 5030,
 '34': 2012,
 '17': 842,
 '44': 2258,
 '2232': 1512,
 'news': 22944,
 'cbnewsk': 8065,
 'att': 5758,
 'paul': 24616,
 'conditt': 9428,
 'insert': 18011,
 'deletion': 11041,
 'aaron': 3892,
 'discourse': 11701,
 'ref': 27304,
 'galatians': 15060,
 '19': 966,
 '20': 1341,
 'obvious': 23541,
 'speaking': 30330,
 'acts': 4211,
 'flesh': 14440,
 'just': 19076,
 'emotions': 12902,
 'themselves': 32163,
 'moral': 22200,
 'immoral': 17423,
 'bad': 6057,
 'first': 14357,
 'label': 19649,
 'emotion': 12898,
 'numb': 23362,
 'ourselves': 24050,
 'hide': 16562,
 'god': 15521,
 'accepts': 4045,
 'us': 33847,
 'oh': 23660,
 'definitely': 10983,
 'colossians': 9056,
 'ephesians': 13192,
 '27': 1700,
 'controlled': 9774,
 'puts': 26572,
 'strong': 31000,
 'emphasis': 12911,
 'self': 29171,
 'write': 35346,
 'timothy': 32435,
 'making': 20868,
 'sure': 31394,
 'teach': 31849,
 'remainder': 27525,
 'paragraph': 24411,
 'think': 32253,
 'quick': 26724,
 'judge': 19014,
 'forgiven': 14656,
 'aids': 4566,
 'dealt': 10802,
 'taken': 31711,
 'responsibility': 27840,
 'appropriate': 5319,
 'choices': 8499,
 'read': 27049,
 'yourself': 35651,
 'joe': 18869,
 'again': 4486,
 'issue': 18542,
 'especially': 13351,
 'over': 24108,
 'stem': 30741,
 'instances': 18051,
 'giving': 15408,
 'soon': 30208,
 'moore': 22193,
 'aldridge': 4661,
 'netcom': 22861,
 'jacquelin': 18627,
 'teenage': 31893,
 'acne': 4165,
 'line': 20242,
 'communication': 9171,
 'services': 29306,
 '408': 2198,
 '241': 1599,
 '9760': 3432,
 'guest': 15907,
 'pchurch': 24668,
 'swell': 31528,
 'actrix': 4210,
 'gen': 15195,
 'nz': 23432,
 'pat': 24565,
 'churchill': 8612,
 'usual': 33889,
 'spotty': 30494,
 'chin': 8470,
 'greasy': 15742,
 'nose': 23240,
 'bought': 7073,
 'him': 16603,
 'clearasil': 8777,
 'face': 13892,
 'wash': 34705,
 'ointment': 23671,
 'probably': 26085,
 'diet': 11505,
 'product': 26136,
 'called': 7718,
 'dalacin': 10602,
 'used': 33860,
 'prescription': 25907,
 'treatment': 32847,
 'available': 5906,
 'chemist': 8406,
 'counter': 10006,
 'asked': 5580,
 'couple': 10028,
 'pharmacists': 24998,
 'either': 12711,
 'severe': 29337,
 'ok': 23674,
 'odd': 23589,
 'spots': 30493,
 'teenager': 31894,
 'nothing': 23264,
 'serious': 29285,
 'father': 14060,
 'figure': 14272,
 'escalate': 13330,
 'disfiguring': 11735,
 'kids': 19336,
 'senstitive': 29229,
 'appearance': 5267,
 'wary': 34702,
 'neighbour': 22816,
 'wierd': 35031,
 'malady': 20873,
 'eventually': 13501,
 'down': 12176,
 'overdose': 24121,
 'vitamin': 34417,
 'scaliness': 28779,
 'around': 5489,
 'hairline': 16038,
 'scalp': 28783,
 'sort': 30233,
 'cradle': 10109,
 'cap': 7820,
 'pointers': 25445,
 'advice': 4399,
 'tried': 32898,
 'anti': 5138,
 'dandruff': 10633,
 'shampoos': 29412,
 'inclined': 17601,
 'condition': 9423,
 'worse': 35295,
 'better': 6557,
 'shall': 29399,
 'bury': 7463,
 'kid': 19330,
 'till': 32409,
 '21': 1421,
 'lucky': 20599,
 'ones': 23746,
 'little': 20342,
 'luck': 20597,
 'skin': 29864,
 'gets': 15322,
 'oily': 23668,
 'really': 27088,
 'miserable': 21898,
 'pimples': 25200,
 'dry': 12294,
 'frequent': 14848,
 'lukewarm': 20613,
 'water': 34727,
 'rinses': 28120,
 'getting': 15323,
 'thing': 32249,
 'under': 33410,
 'simple': 29724,
 'submerging': 31093,
 'bathwater': 6253,
 'softened': 30112,
 'washing': 34709,
 'taking': 31716,
 'mineral': 21814,
 'heard': 16336,
 'iodine': 18380,
 'causes': 8037,
 'trouble': 32962,
 'fast': 14048,
 'food': 14581,
 'restaurants': 27850,
 'sterilize': 30766,
 'equipment': 13256,
 'where': 34938,
 'foods': 14583,
 'came': 7746,
 'grease': 15741,
 'immediately': 17410,
 'removed': 27567,
 'eating': 12524,
 'meat': 21356,
 'keeping': 19213,
 'hair': 16036,
 'rinse': 28119,
 'mousse': 22315,
 'dip': 11599,
 'spray': 30502,
 'warm': 34672,
 'bath': 6248,
 'soaks': 30071,
 'cloths': 8865,
 'soften': 30111,
 'oil': 23667,
 'pores': 25580,
 'prevent': 25983,
 'blackheads': 6774,
 'hydrophilic': 17093,
 'loves': 20543,
 'softens': 30113,
 'washes': 34708,
 'chance': 8278,
 'goes': 15541,
 'limp': 20226,
 'oilyness': 23669,
 'becoming': 6342,
 'convinced': 9820,
 'best': 6540,
 'whitehead': 34973,
 'leave': 19926,
 'alone': 4787,
 'days': 10760,
 'pimple': 25199,
 'misery': 21901,
 'prying': 26386,
 'black': 6773,
 'whiteheads': 34974,
 'infections': 17796,
 'red': 27255,
 'usually': 33891,
 'break': 7167,
 'naturally': 22686,
 'won': 35217,
 'infection': 17795,
 'afterwards': 4479,
 'normal': 23210,
 'cosmetic': 9970,
 'industry': 17742,
 'makes': 20866,
 'money': 22135,
 'selling': 29180,
 'idea': 17219,
 'incredible': 17650,
 'defect': 10949,
 'hidden': 16561,
 'cost': 9981,
 'causing': 8039,
 'jackie': 18618,
 'geb': 15173,
 'pitt': 25234,
 'gordon': 15591,
 'banks': 6140,
 'blindsight': 6838,
 'reply': 27664,
 'pittsburgh': 25237,
 'science': 28897,
 '18': 896,
 'werner': 34881,
 '240393161954': 1594,
 'tol7mac15': 32522,
 'soe': 30105,
 'berkeley': 6507,
 'john': 18880,
 '19213': 995,
 'uucp': 33940,
 'wrote': 35363,
 'explain': 13733,
 'thought': 32298,
 'types': 33142,
 'cones': 9444,
 'equivalent': 13259,
 'rgb': 28011,
 'basically': 6223,
 'right': 28089,
 'sensitive': 29222,
 'green': 15755,
 'blue': 6882,
 'yellow': 35597,
 'two': 33125,
 'common': 9158,
 'kinds': 19378,
 'color': 9045,
 'blindness': 6836,
 'yes': 35601,
 'remember': 27543,
 'now': 23301,
 'contrary': 9748,
 'original': 23940,
 'respondent': 27832,
 'claimed': 8715,
 'n3jxp': 22582,
 'skepticism': 29848,
 'chastity': 8362,
 'intellect': 18117,
 'cadre': 7665,
 'dsl': 12307,
 'shameful': 29408,
 'surrender': 31424,
 'too': 32570,
 'libman': 20133,
 'hsc': 16954,
 'usc': 33853,
 'marlena': 21053,
 'patient': 24593,
 'relationship': 27459,
 'southern': 30259,
 'california': 7711,
 'los': 20506,
 'angeles': 5026,
 'ca': 7643,
 '64': 2667,
 'situation': 29813,
 'occurred': 23566,
 'between': 6561,
 'physican': 25115,
 'upset': 33808,
 'saw': 28747,
 'recurring': 27248,
 'pain': 24296,
 'suggested': 31218,
 'medication': 21389,
 'course': 10037,
 'told': 32523,
 'begin': 6381,
 'monitor': 22140,
 'its': 18585,
 'effectiveness': 12660,
 'general': 15209,
 'health': 16328,
 'exactly': 13552,
 'reaching': 27038,
 'secretary': 29094,
 'explained': 13737,
 'her': 16470,
 'following': 14565,
 'request': 27727,
 'worried': 35290,
 'episodes': 13215,
 'effective': 12658,
 'words': 35249,
 'whatever': 34924,
 'busy': 7479,
 'time': 32417,
 'chit': 8493,
 'chat': 8363,
 'simply': 29736,
 'instructions': 18080,
 '7th': 3052,
 'status': 30696,
 'feeling': 14137,
 'talk': 31723,
 'responded': 27831,
 'spit': 30445,
 'said': 28573,
 'raised': 26849,
 'voice': 34463,
 'started': 30661,
 'quickly': 26727,
 'nervousness': 22847,
 'interfered': 18176,
 'choice': 8498,
 'stuttered': 31052,
 ...}

In [74]:

y = [1, 1, 0, 1, 0, 0, 0]
X = ['marcel', 'josé', 'maria', 'joão', 'mariana', 'adriana', 'adriana']


y = pd.Series(y)

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X)
X_train_counts.shape
#X_train_counts.toarray()[0]

v2 = count_vect.vocabulary_
v2

{'marcel': 3, 'josé': 1, 'maria': 4, 'joão': 2, 'mariana': 5, 'adriana': 0}

In [76]:
import pandas as pd
df = pd.DataFrame.from_dict(v2, orient='index')
df = pd.DataFrame(df)
df.reset_index(level=0, inplace=True)
df.columns = ['name', 'hash']


#df['h2'] = df.apply(lambda x: x['name'], axis=1)
df['h2'] = df.apply(lambda x: x['name'], axis=1)



df['h2'] = df['h2'].map(v2)
df

      name  hash  h2
0   marcel     3   3
1     josé     1   1
2    maria     4   4
3     joão     2   2
4  mariana     5   5
5  adriana     0   0

In [156]:
import numpy as np
y = [1, 1, 0, 1, 0, 0, 0]
X = ['marcel', 'josé', 'maria', 'joão', 'mariana', 'adriana', 'adriana']

y = pd.Series(y)
X = pd.Series(X)

conc = pd.concat([X, y], axis=1)
conc.columns = ['name', 'male']
conc = conc.drop_duplicates()
X = np.array(conc.loc[:, 'name'])


from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X)
X_train_counts.shape
#X_train_counts.toarray()[0]

v2 = count_vect.vocabulary_
conc

      name  male
0   marcel     1
1     josé     1
2    maria     0
3     joão     1
4  mariana     0
5  adriana     0

In [2]:
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

import numpy as np

In [4]:
celsius_q    = np.array([-40, -10,  0,  8, 15, 22,  38],  dtype=float)
fahrenheit_a = np.array([-40,  14, 32, 46, 59, 72, 100],  dtype=float)

for i,c in enumerate(celsius_q):
  print("{} degrees Celsius = {} degrees Fahrenheit".format(c, fahrenheit_a[i]))

-40.0 degrees Celsius = -40.0 degrees Fahrenheit
-10.0 degrees Celsius = 14.0 degrees Fahrenheit
0.0 degrees Celsius = 32.0 degrees Fahrenheit
8.0 degrees Celsius = 46.0 degrees Fahrenheit
15.0 degrees Celsius = 59.0 degrees Fahrenheit
22.0 degrees Celsius = 72.0 degrees Fahrenheit
38.0 degrees Celsius = 100.0 degrees Fahrenheit

In [16]:
l0 = tf.keras.layers.Dense(units=1, input_shape=[1])  
model = tf.keras.Sequential([l0])

model.compile(loss='mean_squared_error',
              optimizer=tf.keras.optimizers.Adam(0.01))

history = model.fit(celsius_q, fahrenheit_a, epochs=20000, verbose=False)
print("Finished training the model")

KeyboardInterrupt: