In [4]:
import numpy as np
import pandas as pd
from soundex import *

df = pd.read_csv('parte_nome_sexo.csv')
df

df = df[df['PrimeiroNomeNoAccents'].notna()]
#df = df[:10000]

In [5]:
df['Sounde'] = df.apply(lambda row: soundex(row['PrimeiroNomeNoAccents']), axis=1)

In [6]:
df[df['Masculino'] == df['Feminino']]

Empty DataFrame
Columns: [Masculino, Feminino, PrimeiroNomeNoAccents, Sounde]
Index: []

In [7]:
df['SoundexIndice0'] = df[df['Sounde'].notna()].apply(lambda row: ord(row['Sounde'][0:1]), axis=1)
print('ok indice 0')

df['SoundexIndice1'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][1:2]), axis=1)
print('ok indice 1')

df['SoundexIndice2'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][2:3]), axis=1)
print('ok indice 2')

df['SoundexIndice3'] = df[df['Sounde'].notna()].apply(lambda row: int(row['Sounde'][3:4]), axis=1)
print('ok indice 3')

In [8]:
df['Leng'] = df.apply(lambda row: len(row['PrimeiroNomeNoAccents']), axis=1)

In [9]:
df.drop(['PrimeiroNomeNoAccents', 'Sounde'], axis=1)

,Masculino,Feminino,SoundexIndice0,SoundexIndice1,SoundexIndice2,SoundexIndice3,Leng
0,1,0,98,5,3,0,8
1,1,0,115,2,6,3,10
2,1,0,108,2,0,0,4
3,1,0,100,5,4,0,6
4,1,0,109,6,2,0,6
5,1,0,97,3,0,0,4
6,1,0,119,4,3,6,6
7,0,1,115,5,0,0,5
8,1,0,109,6,2,0,6
9,0,1,107,1,5,0,6
10,1,0,118,4,3,6,7
11,0,1,108,5,0,0,4
12,1,0,108,2,0,0,4
13,1,0,101,2,5,0,7
14,0,1,99,4,0,0,5
15,0,1,105,4,5,0,4
16,1,0,99,6,4,2,6
17,1,0,100,2,0,0,5
18,0,1,110,2,4,5,9
19,0,1,101,1,4,5,7
20,1,0,99,6,4,2,6
21,1,0,111,3,5,6,6
22,1,0,106,2,5,4,7
23,1,0,97,3,4,3,8
24,1,0,98,5,2,5,8
25,1,0,101,3,5,4,8
26,1,0,101,3,2,5,5
27,1,0,97,5,3,6,8
28,1,0,102,4,1,0,6
29,1,0,106,0,0,0,4
...,...,...,...,...,...,...,...
999970,0,1,118,5,2,0,7
999971,1,0,106,2,0,0,4
999972,0,1,101,3,4,2,8
999973,0,1,110,3,0,0,5
999974,0,1,106,2,4,5,9
999975,0,1,99,4,5,6,6
999976,0,1,114,2,5,0,6
999977,0,1,99,4,5,2,8
999978,1,0,114,2,6,0,7
999979,1,0,97,4,2,3,7
999980,0,1,99,4,5,2,8
999981,0,1,114,2,5,4,9
999982,1,0,111,1,3,0,6
999983,1,0,106,6,2,0,5
999984,0,1,106,3,0,0,6
999985,0,1,105,6,5,0,5
999986,1,0,108,2,0,0,4
999987,0,1,97,4,5,2,9
999988,1,0,114,5,1,4,9
999989,0,1,101,4,5,0,6
999990,1,0,101,2,1,4,7
999991,1,0,103,6,2,5,8
999992,1,0,109,5,4,0,6
999993,0,1,100,1,6,0,6
999994,1,0,101,1,6,4,8
999995,0,1,109,6,4,2,8
999996,1,0,104,5,4,3,8
999997,0,1,101,1,5,6,6
999998,0,1,109,6,0,0,5
999999,1,0,101,1,6,3,7

In [10]:
df

,Masculino,Feminino,PrimeiroNomeNoAccents,Sounde,SoundexIndice0,SoundexIndice1,SoundexIndice2,SoundexIndice3,Leng
0,1,0,BENEDITO,b530,98,5,3,0,8
1,1,0,Secretario,s263,115,2,6,3,10
2,1,0,LUIZ,l200,108,2,0,0,4
3,1,0,DANIEL,d540,100,5,4,0,6
4,1,0,MARCOS,m620,109,6,2,0,6
5,1,0,ADAO,a300,97,3,0,0,4
6,1,0,WALDIR,w436,119,4,3,6,6
7,0,1,Sonia,s500,115,5,0,0,5
8,1,0,MARCOS,m620,109,6,2,0,6
9,0,1,Keviny,k150,107,1,5,0,6
10,1,0,Valdeir,v436,118,4,3,6,7
11,0,1,LENI,l500,108,5,0,0,4
12,1,0,LUIS,l200,108,2,0,0,4
13,1,0,EUGENIO,e250,101,2,5,0,7
14,0,1,CELIA,c400,99,4,0,0,5
15,0,1,Ilma,i450,105,4,5,0,4
16,1,0,CARLOS,c642,99,6,4,2,6
17,1,0,Diego,d200,100,2,0,0,5
18,0,1,NEUSALINA,n245,110,2,4,5,9
19,0,1,Evelini,e145,101,1,4,5,7
20,1,0,CARLOS,c642,99,6,4,2,6
21,1,0,Odemir,o356,111,3,5,6,6
22,1,0,JOSENIL,j254,106,2,5,4,7
23,1,0,Adeilton,a343,97,3,4,3,8
24,1,0,Benjamin,b525,98,5,2,5,8
25,1,0,EDMILSON,e354,101,3,5,4,8
26,1,0,EDSON,e325,101,3,2,5,5
27,1,0,Anderson,a536,97,5,3,6,8
28,1,0,FLAVIO,f410,102,4,1,0,6
29,1,0,Joao,j000,106,0,0,0,4
...,...,...,...,...,...,...,...,...,...
999970,0,1,Vanessa,v520,118,5,2,0,7
999971,1,0,JOSE,j200,106,2,0,0,4
999972,0,1,Edileuza,e342,101,3,4,2,8
999973,0,1,NEIDE,n300,110,3,0,0,5
999974,0,1,JAQUELINE,j245,106,2,4,5,9
999975,0,1,Clemir,c456,99,4,5,6,6
999976,0,1,REGINA,r250,114,2,5,0,6
999977,0,1,CLEONICE,c452,99,4,5,2,8
999978,1,0,Rogerio,r260,114,2,6,0,7
999979,1,0,Alcides,a423,97,4,2,3,7
999980,0,1,CLEONICE,c452,99,4,5,2,8
999981,0,1,Rosenilda,r254,114,2,5,4,9
999982,1,0,Ovidio,o130,111,1,3,0,6
999983,1,0,JERGE,j620,106,6,2,0,5
999984,0,1,Judite,j300,106,3,0,0,6
999985,0,1,IRENE,i650,105,6,5,0,5
999986,1,0,LUIZ,l200,108,2,0,0,4
999987,0,1,Almezinda,a452,97,4,5,2,9
999988,1,0,RONIVALDO,r514,114,5,1,4,9
999989,0,1,ELOINA,e450,101,4,5,0,6
999990,1,0,Espolio,e214,101,2,1,4,7
999991,1,0,Grasimar,g625,103,6,2,5,8
999992,1,0,MANOEL,m540,109,5,4,0,6
999993,0,1,Debora,d160,100,1,6,0,6
999994,1,0,Everaldo,e164,101,1,6,4,8
999995,0,1,Mariluci,m642,109,6,4,2,8
999996,1,0,HAMILTON,h543,104,5,4,3,8
999997,0,1,EVANIR,e156,101,1,5,6,6
999998,0,1,MARIA,m600,109,6,0,0,5
999999,1,0,EVERTON,e163,101,1,6,3,7

In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = df.drop(['Masculino', 'Feminino', 'PrimeiroNomeNoAccents', 'Sounde'], axis=1)
y = df.loc[:, 'Masculino']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.33, random_state=7)

X
#est = RandomForestClassifier(n_estimators = 40).fit(X, y)
#est.score(X, y)

#est = reg

        SoundexIndice0  SoundexIndice1  SoundexIndice2  SoundexIndice3  Leng
0                   98               5               3               0     8
1                  115               2               6               3    10
2                  108               2               0               0     4
3                  100               5               4               0     6
4                  109               6               2               0     6
5                   97               3               0               0     4
6                  119               4               3               6     6
7                  115               5               0               0     5
8                  109               6               2               0     6
9                  107               1               5               0     6
10                 118               4               3               6     7
11                 108               5               0               0     4
12                 108               2               0               0     4
13                 101               2               5               0     7
14                  99               4               0               0     5
15                 105               4               5               0     4
16                  99               6               4               2     6
17                 100               2               0               0     5
18                 110               2               4               5     9
19                 101               1               4               5     7
20                  99               6               4               2     6
21                 111               3               5               6     6
22                 106               2               5               4     7
23                  97               3               4               3     8
24                  98               5               2               5     8
25                 101               3               5               4     8
26                 101               3               2               5     5
27                  97               5               3               6     8
28                 102               4               1               0     6
29                 106               0               0               0     4
...                ...             ...             ...             ...   ...
999970             118               5               2               0     7
999971             106               2               0               0     4
999972             101               3               4               2     8
999973             110               3               0               0     5
999974             106               2               4               5     9
999975              99               4               5               6     6
999976             114               2               5               0     6
999977              99               4               5               2     8
999978             114               2               6               0     7
999979              97               4               2               3     7
999980              99               4               5               2     8
999981             114               2               5               4     9
999982             111               1               3               0     6
999983             106               6               2               0     5
999984             106               3               0               0     6
999985             105               6               5               0     5
999986             108               2               0               0     4
999987              97               4               5               2     9
999988             114               5               1               4     9
999989             101               4               5               0     6
999990             101               2               1               4     7
999991             103               6               2               5     8
999992             109               5               4               0     6
999993             100               1               6               0     6
999994             101               1               6               4     8
999995             109               6               4               2     8
999996             104               5               4               3     8
999997             101               1               5               6     6
999998             109               6               0               0     5
999999             101               1               6               3     7

[946203 rows x 5 columns]

In [12]:
# TODO: Import 'make_scorer', 'DecisionTreeRegressor', and 'GridSearchCV'
from sklearn.metrics import make_scorer
from sklearn.tree import DecisionTreeRegressor 
from sklearn.model_selection import ShuffleSplit, GridSearchCV


# O fit_model(...) cria uma um estimador de árvore de decisão, faz o CV do parâmetro 'max_depth' de 1 a 10, depois faz um Grid Search CV, e retorna o grid.best_estimator_;
def fit_model(X, y):
    """ Performs grid search over the 'max_depth' parameter for a 
        decision tree regressor trained on the input data [X, y]. """
    
    # Create cross-validation sets from the training data
    # sklearn version 0.18: ShuffleSplit(n_splits=10, test_size=0.1, train_size=None, random_state=None)
    cv_sets = ShuffleSplit(n_splits=5, test_size = 0.20, random_state = 0)

    # TODO: Create a decision tree regressor object
    regressor = RandomForestClassifier()

    # TODO: Create a dictionary for the parameter 'max_depth' with a range from 1 to 10
    #params = {"n_estimators":[10, 20, 40, 80, 200]}

    param_grid = { 
        #'n_estimators': [200, 500, 2000],
        'n_estimators': [200],
        #'max_features': ['auto', 'sqrt', 'log2'],
        'max_depth' : [12,20],
        'max_depth' : [12],
        'criterion' :['gini', 'entropy']
        #'criterion' :['gini']
    }
    
    # TODO: Create the grid search object
    grid = GridSearchCV(regressor, param_grid, cv=cv_sets)

    # Fit the grid search object to the data to compute the optimal model
    grid = grid.fit(X, y)

    # Return the optimal model after fitting the data
    return grid.best_estimator_

In [13]:
param_grid = {
        'n_estimators': 200,
        'max_depth' : 12,
        'criterion' :'gini'
    }



# Fit the training data to the model using grid search
#est = fit_model(X_train, y_train)
est = RandomForestClassifier(**param_grid)
est.fit(X, y)

print(est.get_params())

{'bootstrap': True, 'class_weight': None, 'criterion': 'gini', 'max_depth': 12, 'max_features': 'auto', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 200, 'n_jobs': 1, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}

In [14]:
est.score(X, y)

0.8440503781957994

In [15]:
est.score(X_test, y_test)

0.8433900085509228

In [16]:
est.score(X_train, y_train)

0.8443756349021068

In [17]:
import pickle
s = pickle.dumps(est)
clf2 = pickle.loads(s)
clf2.score(X_train, y_train)

0.8443756349021068

In [18]:
from sklearn.externals import joblib

In [20]:
joblib.dump(est, 'modelo_soundex.pkl', compress=9)

['my_model_soundex.pkl']